server{ 
	listen 127.0.0.1:4242;

	error_page 404 /data/www/error404.html;

	client_max_body_size 10m;

	location /{
		root /data/www;
		allow_methods: POST GET DELETE;
		autoindex on;
	}

	location /test{
		redirect https://google.fr;
		
		
		
		
		
		autoindex on;
	}
}

server{
	listen	0.0.0.0:4343;

	error_page 404 /data/www/error404.html;

	client_max_body_size 50m;

	location /{
		root ./data;
		allow_methods: POST GET DELETE;
		autoindex on;
		upload_store /var/upload/;
		cgi_pass /cgi/php/php-fpm83;
	}

	location /ABCD {
		root ./data;
		allow_methods: POST GET DELETE;
		autoindex on;
		index index.html;
		upload_store /var/upload/;
		cgi_pass /cgi/php/php-fpm83;
	}

	location /test {
		redirect https://google.fr;
	}
}
